//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiroAlBlancoConsolaApp.RecursosLocalizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiroAlBlancoConsolaApp.RecursosLocalizables.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to the game of Missile Launcher.
        /// </summary>
        internal static string Gretting {
            get {
                return ResourceManager.GetString("Gretting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter missile´s angle (0-90).
        /// </summary>
        internal static string MissileAngle {
            get {
                return ResourceManager.GetString("MissileAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ups, you fail: .
        /// </summary>
        internal static string MissileLose {
            get {
                return ResourceManager.GetString("MissileLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shoots realized:.
        /// </summary>
        internal static string MissileNumber {
            get {
                return ResourceManager.GetString("MissileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter missile´s speed (0-300000).
        /// </summary>
        internal static string MissileSpeed {
            get {
                return ResourceManager.GetString("MissileSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press one to join the game.
        /// </summary>
        internal static string OpcionOne {
            get {
                return ResourceManager.GetString("OpcionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press zero to exit.
        /// </summary>
        internal static string OpcionZero {
            get {
                return ResourceManager.GetString("OpcionZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grettings, you win .
        /// </summary>
        internal static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
    }
}
